// European Emotions Data from Gallup Global Emotions Report 2024
// Each entry represents a country's percentage of people who felt that emotion
// Date received by email

export type Emotion =
  | "Enjoyment"
  | "Well-rested"
  | "Learning"
  | "Worry"
  | "Anger"
  | "Sadness";

export type Country =
  | "Albania"
  | "Armenia"
  | "Austria"
  | "Azerbaijan"
  | "Belgium"
  | "Bosnia and Herzegovina"
  | "Bulgaria"
  | "Croatia"
  | "Cyprus"
  | "Denmark"
  | "Estonia"
  | "Finland"
  | "France"
  | "Georgia"
  | "Germany"
  | "Greece"
  | "Hungary"
  | "Iceland"
  | "Ireland"
  | "Italy"
  | "Kosovo"
  | "Latvia"
  | "Lithuania"
  | "Malta"
  | "Montenegro"
  | "North Macedonia"
  | "Norway"
  | "Poland"
  | "Portugal"
  | "Romania"
  | "Serbia"
  | "Slovakia"
  | "Slovenia"
  | "Spain"
  | "Sweden"
  | "Switzerland"
  | "Ukraine";

export type CountryData = {
  Emotion: string;
  values: Record<Country, number>;
};

export const data: CountryData[] = [
  {
    Emotion: "Anger",
    values: {
      Albania: 21,
      Armenia: 43,
      Austria: 14,
      Azerbaijan: 11,
      Belgium: 11,
      "Bosnia and Herzegovina": 22,
      Bulgaria: 9,
      Croatia: 8,
      Cyprus: 21,
      Denmark: 13,
      Estonia: 8,
      Finland: 5,
      France: 19,
      Georgia: 16,
      Germany: 15,
      Greece: 22,
      Hungary: 12,
      Iceland: 7,
      Ireland: 13,
      Italy: 9,
      Kosovo: 7,
      Latvia: 18,
      Lithuania: 12,
      Malta: 24,
      Montenegro: 18,
      "North Macedonia": 20,
      Norway: 11,
      Poland: 9,
      Portugal: 8,
      Romania: 14,
      Serbia: 13,
      Slovakia: 20,
      Slovenia: 15,
      Spain: 23,
      Sweden: 12,
      Switzerland: 10,
      Ukraine: 21,
    },
  },
  {
    Emotion: "Sadness",
    values: {
      Albania: 28,
      Armenia: 40,
      Austria: 21,
      Azerbaijan: 21,
      Belgium: 19,
      "Bosnia and Herzegovina": 21,
      Bulgaria: 21,
      Croatia: 13,
      Cyprus: 27,
      Denmark: 17,
      Estonia: 21,
      Finland: 11,
      France: 21,
      Georgia: 13,
      Germany: 23,
      Greece: 27,
      Hungary: 20,
      Iceland: 13,
      Ireland: 24,
      Italy: 25,
      Kosovo: 4,
      Latvia: 20,
      Lithuania: 22,
      Malta: 23,
      Montenegro: 15,
      "North Macedonia": 19,
      Norway: 22,
      Poland: 9,
      Portugal: 29,
      Romania: 24,
      Serbia: 15,
      Slovakia: 12,
      Slovenia: 16,
      Spain: 23,
      Sweden: 19,
      Switzerland: 18,
      Ukraine: 38,
    },
  },
  {
    Emotion: "Stress",
    values: {
      Albania: 54,
      Armenia: 30,
      Austria: 33,
      Azerbaijan: 9,
      Belgium: 38,
      "Bosnia and Herzegovina": 31,
      Bulgaria: 27,
      Croatia: 26,
      Cyprus: 60,
      Denmark: 20,
      Estonia: 28,
      Finland: 32,
      France: 35,
      Georgia: 17,
      Germany: 36,
      Greece: 57,
      Hungary: 33,
      Iceland: 38,
      Ireland: 38,
      Italy: 43,
      Kosovo: 20,
      Latvia: 31,
      Lithuania: 20,
      Malta: 52,
      Montenegro: 18,
      "North Macedonia": 30,
      Norway: 37,
      Poland: 16,
      Portugal: 43,
      Romania: 36,
      Serbia: 23,
      Slovakia: 29,
      Slovenia: 31,
      Spain: 38,
      Sweden: 25,
      Switzerland: 29,
      Ukraine: 33,
    },
  },
  {
    Emotion: "Worry",
    values: {
      Albania: 42,
      Armenia: 53,
      Austria: 30,
      Azerbaijan: 20,
      Belgium: 39,
      "Bosnia and Herzegovina": 36,
      Bulgaria: 26,
      Croatia: 47,
      Cyprus: 52,
      Denmark: 36,
      Estonia: 33,
      Finland: 29,
      France: 31,
      Georgia: 23,
      Germany: 31,
      Greece: 51,
      Hungary: 32,
      Iceland: 30,
      Ireland: 32,
      Italy: 44,
      Kosovo: 15,
      Latvia: 34,
      Lithuania: 25,
      Malta: 61,
      Montenegro: 45,
      "North Macedonia": 37,
      Norway: 38,
      Poland: 22,
      Portugal: 52,
      Romania: 35,
      Serbia: 34,
      Slovakia: 33,
      Slovenia: 42,
      Spain: 48,
      Sweden: 32,
      Switzerland: 25,
      Ukraine: 53,
    },
  },
  {
    Emotion: "Pain",
    values: {
      Albania: 49,
      Armenia: 41,
      Austria: 29,
      Azerbaijan: 27,
      Belgium: 28,
      "Bosnia and Herzegovina": 26,
      Bulgaria: 28,
      Croatia: 23,
      Cyprus: 33,
      Denmark: 31,
      Estonia: 25,
      Finland: 24,
      France: 35,
      Georgia: 25,
      Germany: 28,
      Greece: 35,
      Hungary: 28,
      Iceland: 42,
      Ireland: 29,
      Italy: 30,
      Kosovo: 25,
      Latvia: 32,
      Lithuania: 22,
      Malta: 33,
      Montenegro: 31,
      "North Macedonia": 30,
      Norway: 27,
      Poland: 13,
      Portugal: 37,
      Romania: 33,
      Serbia: 22,
      Slovakia: 28,
      Slovenia: 23,
      Spain: 34,
      Sweden: 27,
      Switzerland: 27,
      Ukraine: 35,
    },
  },
  {
    Emotion: "Enjoyment",
    values: {
      Albania: 67,
      Armenia: 59,
      Austria: 75,
      Azerbaijan: 50,
      Belgium: 75,
      "Bosnia and Herzegovina": 68,
      Bulgaria: 71,
      Croatia: 59,
      Cyprus: 76,
      Denmark: 93,
      Estonia: 85,
      Finland: 76,
      France: 75,
      Georgia: 72,
      Germany: 78,
      Greece: 68,
      Hungary: 75,
      Iceland: 88,
      Ireland: 80,
      Italy: 63,
      Kosovo: 80,
      Latvia: 79,
      Lithuania: 74,
      Malta: 64,
      Montenegro: 63,
      "North Macedonia": 66,
      Norway: 81,
      Poland: 71,
      Portugal: 63,
      Romania: 81,
      Serbia: 65,
      Slovakia: 81,
      Slovenia: 64,
      Spain: 64,
      Sweden: 84,
      Switzerland: 79,
      Ukraine: 63,
    },
  },
  {
    Emotion: "Wellrested",
    values: {
      Albania: 54,
      Armenia: 52,
      Austria: 75,
      Azerbaijan: 59,
      Belgium: 67,
      "Bosnia and Herzegovina": 51,
      Bulgaria: 61,
      Croatia: 70,
      Cyprus: 52,
      Denmark: 70,
      Estonia: 64,
      Finland: 69,
      France: 67,
      Georgia: 63,
      Germany: 80,
      Greece: 56,
      Hungary: 51,
      Iceland: 60,
      Ireland: 75,
      Italy: 63,
      Kosovo: 64,
      Latvia: 66,
      Lithuania: 71,
      Malta: 73,
      Montenegro: 58,
      "North Macedonia": 61,
      Norway: 59,
      Poland: 73,
      Portugal: 72,
      Romania: 66,
      Serbia: 65,
      Slovakia: 68,
      Slovenia: 74,
      Spain: 72,
      Sweden: 70,
      Switzerland: 72,
      Ukraine: 47,
    },
  },
  {
    Emotion: "Learned",
    values: {
      Albania: 31,
      Armenia: 43,
      Austria: 62,
      Azerbaijan: 34,
      Belgium: 57,
      "Bosnia and Herzegovina": 47,
      Bulgaria: 36,
      Croatia: 46,
      Cyprus: 46,
      Denmark: 64,
      Estonia: 65,
      Finland: 75,
      France: 59,
      Georgia: 30,
      Germany: 59,
      Greece: 43,
      Hungary: 53,
      Iceland: 65,
      Ireland: 61,
      Italy: 47,
      Kosovo: 38,
      Latvia: 55,
      Lithuania: 53,
      Malta: 54,
      Montenegro: 47,
      "North Macedonia": 37,
      Norway: 69,
      Poland: 33,
      Portugal: 54,
      Romania: 48,
      Serbia: 50,
      Slovakia: 44,
      Slovenia: 56,
      Spain: 60,
      Sweden: 66,
      Switzerland: 65,
      Ukraine: 45,
    },
  },
  {
    Emotion: "Smiled",
    values: {
      Albania: 73,
      Armenia: 61,
      Austria: 71,
      Azerbaijan: 60,
      Belgium: 77,
      "Bosnia and Herzegovina": 66,
      Bulgaria: 64,
      Croatia: 61,
      Cyprus: 73,
      Denmark: 80,
      Estonia: 71,
      Finland: 76,
      France: 67,
      Georgia: 68,
      Germany: 69,
      Greece: 63,
      Hungary: 66,
      Iceland: 86,
      Ireland: 74,
      Italy: 72,
      Kosovo: 76,
      Latvia: 65,
      Lithuania: 74,
      Malta: 78,
      Montenegro: 51,
      "North Macedonia": 49,
      Norway: 76,
      Poland: 64,
      Portugal: 79,
      Romania: 73,
      Serbia: 52,
      Slovakia: 68,
      Slovenia: 66,
      Spain: 76,
      Sweden: 79,
      Switzerland: 68,
      Ukraine: 53,
    },
  },
  {
    Emotion: "Respect",
    values: {
      Albania: 91,
      Armenia: 98,
      Austria: 89,
      Azerbaijan: 87,
      Belgium: 94,
      "Bosnia and Herzegovina": 84,
      Bulgaria: 90,
      Croatia: 84,
      Cyprus: 90,
      Denmark: 95,
      Estonia: 93,
      Finland: 95,
      France: 91,
      Georgia: 95,
      Germany: 88,
      Greece: 89,
      Hungary: 92,
      Iceland: 96,
      Ireland: 88,
      Italy: 94,
      Kosovo: 91,
      Latvia: 91,
      Lithuania: 87,
      Malta: 93,
      Montenegro: 92,
      "North Macedonia": 90,
      Norway: 93,
      Poland: 91,
      Portugal: 96,
      Romania: 92,
      Serbia: 91,
      Slovakia: 89,
      Slovenia: 95,
      Spain: 91,
      Sweden: 96,
      Switzerland: 88,
      Ukraine: 89,
    },
  },
];
